# Address config
address: ":6881"

# UDP config
read-buffer-size: 10240
send-queue-size: 1024
node-queue-size: 1024

# KRPC config
send-message-speed: 10 # unit millisecond
prime-nodes:
  - "router.bittorrent.com:6881"
  - "router.utorrent.com:6881"
  - "dht.transmissionbt.com:6881"
transaction-keep-time: 15  # uint second
transaction-ticker-time: 15  # uint second

# DHT config
find-node-speed: 1000  # uint millisecond

# routing config
expiration-time: 15  # uint minute

# acquirer config
acquirer-max-size: 1024
acquirer-interval-time: 2 # unit second

# DataBase
database-type: "sqlite3"
database-file-name: "data.db"

